# openapi2-functions.yaml
swagger: '2.0'
info:
  title: my-api This is a test api gateway
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  user: 
    type: object
    properties: 
      id: 
        type: integer
      email: 
        type: string
      is_admin: 
        type: integer
      has_logged: 
        type: integer
      status: 
        type: integer
      user_settings: 
        type: object
        properties: 
          user_id: 
            type: integer
          name: 
            type: string
          phone: 
            type: string
          status: 
            type: integer
          short_date_format: 
            type: string
          short_time_format: 
            type: string
          decimal_separators: 
            type: string
          thousands_separators: 
            type: string
          distance_unit: 
            type: string
          language: 
            type: string
          country: 
            type: string
          timezone: 
            type: string
          volumetric_measurement_unit: 
            type: integer
          created: 
            type: string
          modified: 
            type: string
          currency: 
            type: string
      organization_settings: 
        type: object
        properties: 
          currency: 
            type: string
          country: 
            type: string
          consultant_user: 
            type: string
      organization_id: 
        type: integer
      organization_status: 
        type: integer
      role_id: 
        type: integer
      company_name: 
        type: string
      vehicles: 
        type: array
        items: 
          type: integer
      groups: 
        type: array
        items: 
          type: string
      clients: 
        type: array
        items: 
          type: integer
  user_body:
    additionalProperties: false
    type: "object"
    required:
      - "user"
    properties:
      user:
        $ref: "#/definitions/user"
  generate_response:
    additionalProperties: false
    type: "object"
    required:
      - "token"
    properties:
      token:
        type: string
paths:
  /v1/hello:
    get:
      summary: Hi Service
      operationId: hello-v1
      security:
        - Bearer: []
      x-google-backend:
        address: https://hello-bpt6mfm6tq-uc.a.run.app
      responses:
        '200':
          description: OK
  /api/v2/generate:
    post:
      operationId: generate
      x-google-backend:
        address: https://api-jwt-generator-bpt6mfm6tq-uc.a.run.app
      parameters:
        - in: "body"
          name: "user"
          description: "All user data"
          required: true
          schema:
            $ref: "#/definitions/user_body"
      responses:
        '200':
          description: A successful response
          schema:
            $ref: "#/definitions/generate_response"
securityDefinitions:
  Bearer:
    authorizationUrl: "https://auth-test-bpt6mfm6tq-uc.a.run.app/authorized"
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "serviceaccountadmin@targaren-cli.iam.gserviceaccount.com"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/serviceaccountadmin@targaren-cli.iam.gserviceaccount.com"
    x-google-audiences: "cloudrun:*"