version: '3'
services:

  api-jwt-generator:
    image: api-jwt-generator
    container_name: api-jwt-generator
    build:
      context: ./api-jwt-generator
      dockerfile: Dockerfile.dev
    environment:
      PORT: 8080
      JWT_AUDIENCE:
      SERVICE_ACCOUNT_CLIENT_EMAIL:
      SERVICE_ACCOUNT_PRIVATE_KEY:
    ports:
      - 8080:8080
  api-auth:
    image: api-auth
    container_name: api-auth
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    environment:
      PORT: 8081
      JWT_AUDIENCE:
      JWK_URI:
      JWT_ISSUER:
    ports:
      - 8081:8081   