on:
  push:
    branches:
      - main
    paths:
      - 'cgv-api-gateway/**'

name: Deploy/Update Api Gateway 
env:
  REGION: ${{ secrets.REGION }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

defaults:
  run:
    shell: bash
    working-directory: cgv-api-gateway

jobs:
  deploy-revision:
      runs-on: ubuntu-latest
      environment: production
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
      steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve